### ISSUE TITLE
Specify the date formats used in formatting entries for createSimpleLogger 

### ISSUE THREAD

**Issue by ltamrazov** [darrylwest/simple-node-logger#2]
Hi,

I wanted to simply specify the date formats used in formatting entries for createSimpleLogger and createSimpleFileLogger. I didn't see functionality for changing them from "HH:mm:ss:SSS" to something else. I created a pull-request (#1) , but thought maybe you missed it. What do you think? Did I miss anything in it? 

Thanks,

**Comment by ltamrazov** [comment]
@raincity any thoughts on this?

**Comment by darrylwest** [comment]
Hi,

Sorry for the delay, I just noticed your pull request.   I like the idea of having the ability to supply options (opts) to the constructor, especially to change formatting but give me some time to run it by my team to see what they think.

thanks, darryl...

**Comment by ltamrazov** [comment]
Great, thanks.

**Comment by darrylwest** [comment]
The change I made was to allow either a logFilePath string or options object to be passed to the factory constructors createSimpleLogger and createSimpleFileLogger and added a timestampFormat property to AbstractAppender to pick off the custom format or use the default if none was supplied.

I had a bit of trouble with the unit tests because of time zone differences between me, my team and travis ci, but other than that it was an easy change.

Documents and examples are updated.  Hope this is what you were looking for.

thanks,

darryl

**Comment by ltamrazov** [comment]
Awesome. Thanks a lot.
